[build]
  functions = "dist/functions"

[[redirects]]
  from = "/api/*"
  to = "https://merchants.api.sandbox-utrust.com/api/:splat"
  headers = {Authorization = "Bearer u_test_api_f0d624b9-4c33-43bb-8737-d600222c6eb4"}

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
