backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: products
    label: Products
    folder: src/pages
    create: true
    identifier_field: name
    fields:
      - { name: 'templateKey', label: 'Template Key', default: 'product-page' }
      - { name: path, label: Path, hint: 'E.g.: /chess-match' }
      - { name: name, label: Name }
      - {
          name: description,
          label: Description,
          hint: 'This text will appear on the product page only',
        }
      - {
          name: image,
          label: Image,
          widget: image,
          allow_multiple: false,
          hint: 'Respect the 500x500 pixels',
        }
      - {
          name: price,
          label: Price,
          hint: 'E.g.: 10.00 - dont forget the 00 after the comma',
        }
